
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	private global::Gtk.Entry cajatexto;
	private global::Gtk.Table table1;
	private global::Gtk.Button BEntre;
	private global::Gtk.Button BIgual;
	private global::Gtk.Button BMas;
	private global::Gtk.Button BMenos;
	private global::Gtk.Button BN;
	private global::Gtk.Button BN1;
	private global::Gtk.Button BN2;
	private global::Gtk.Button BN3;
	private global::Gtk.Button BN4;
	private global::Gtk.Button BN5;
	private global::Gtk.Button BN6;
	private global::Gtk.Button BN7;
	private global::Gtk.Button BN8;
	private global::Gtk.Button BN9;
	private global::Gtk.Button BPor;
	private global::Gtk.Button BPunto;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.cajatexto = new global::Gtk.Entry ();
		this.cajatexto.CanFocus = true;
		this.cajatexto.Name = "cajatexto";
		this.cajatexto.IsEditable = true;
		this.cajatexto.InvisibleChar = '●';
		this.vbox1.Add (this.cajatexto);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.cajatexto]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.table1 = new global::Gtk.Table (((uint)(4)), ((uint)(4)), false);
		this.table1.Name = "table1";
		this.table1.RowSpacing = ((uint)(6));
		this.table1.ColumnSpacing = ((uint)(6));
		// Container child table1.Gtk.Table+TableChild
		this.BEntre = new global::Gtk.Button ();
		this.BEntre.CanFocus = true;
		this.BEntre.Name = "BEntre";
		this.BEntre.UseUnderline = true;
		this.BEntre.Label = global::Mono.Unix.Catalog.GetString ("/");
		this.table1.Add (this.BEntre);
		global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1 [this.BEntre]));
		w2.TopAttach = ((uint)(3));
		w2.BottomAttach = ((uint)(4));
		w2.LeftAttach = ((uint)(3));
		w2.RightAttach = ((uint)(4));
		w2.XOptions = ((global::Gtk.AttachOptions)(4));
		w2.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.BIgual = new global::Gtk.Button ();
		this.BIgual.CanFocus = true;
		this.BIgual.Name = "BIgual";
		this.BIgual.UseUnderline = true;
		this.BIgual.Label = global::Mono.Unix.Catalog.GetString ("=");
		this.table1.Add (this.BIgual);
		global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1 [this.BIgual]));
		w3.TopAttach = ((uint)(3));
		w3.BottomAttach = ((uint)(4));
		w3.LeftAttach = ((uint)(2));
		w3.RightAttach = ((uint)(3));
		w3.XOptions = ((global::Gtk.AttachOptions)(4));
		w3.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.BMas = new global::Gtk.Button ();
		this.BMas.CanFocus = true;
		this.BMas.Name = "BMas";
		this.BMas.UseUnderline = true;
		this.BMas.Label = global::Mono.Unix.Catalog.GetString ("+");
		this.table1.Add (this.BMas);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1 [this.BMas]));
		w4.LeftAttach = ((uint)(3));
		w4.RightAttach = ((uint)(4));
		w4.XOptions = ((global::Gtk.AttachOptions)(4));
		w4.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.BMenos = new global::Gtk.Button ();
		this.BMenos.CanFocus = true;
		this.BMenos.Name = "BMenos";
		this.BMenos.UseUnderline = true;
		this.BMenos.Label = global::Mono.Unix.Catalog.GetString ("-");
		this.table1.Add (this.BMenos);
		global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1 [this.BMenos]));
		w5.TopAttach = ((uint)(1));
		w5.BottomAttach = ((uint)(2));
		w5.LeftAttach = ((uint)(3));
		w5.RightAttach = ((uint)(4));
		w5.XOptions = ((global::Gtk.AttachOptions)(4));
		w5.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.BN = new global::Gtk.Button ();
		this.BN.CanFocus = true;
		this.BN.Name = "BN";
		this.BN.UseUnderline = true;
		this.BN.Label = global::Mono.Unix.Catalog.GetString ("0");
		this.table1.Add (this.BN);
		global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1 [this.BN]));
		w6.TopAttach = ((uint)(3));
		w6.BottomAttach = ((uint)(4));
		w6.XOptions = ((global::Gtk.AttachOptions)(4));
		w6.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.BN1 = new global::Gtk.Button ();
		this.BN1.CanFocus = true;
		this.BN1.Name = "BN1";
		this.BN1.UseUnderline = true;
		this.BN1.Label = global::Mono.Unix.Catalog.GetString ("1");
		this.table1.Add (this.BN1);
		global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1 [this.BN1]));
		w7.XOptions = ((global::Gtk.AttachOptions)(4));
		w7.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.BN2 = new global::Gtk.Button ();
		this.BN2.CanFocus = true;
		this.BN2.Name = "BN2";
		this.BN2.UseUnderline = true;
		this.BN2.Label = global::Mono.Unix.Catalog.GetString ("2");
		this.table1.Add (this.BN2);
		global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1 [this.BN2]));
		w8.LeftAttach = ((uint)(1));
		w8.RightAttach = ((uint)(2));
		w8.XOptions = ((global::Gtk.AttachOptions)(4));
		w8.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.BN3 = new global::Gtk.Button ();
		this.BN3.CanFocus = true;
		this.BN3.Name = "BN3";
		this.BN3.UseUnderline = true;
		this.BN3.Label = global::Mono.Unix.Catalog.GetString ("3");
		this.table1.Add (this.BN3);
		global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1 [this.BN3]));
		w9.LeftAttach = ((uint)(2));
		w9.RightAttach = ((uint)(3));
		w9.XOptions = ((global::Gtk.AttachOptions)(4));
		w9.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.BN4 = new global::Gtk.Button ();
		this.BN4.CanFocus = true;
		this.BN4.Name = "BN4";
		this.BN4.UseUnderline = true;
		this.BN4.Label = global::Mono.Unix.Catalog.GetString ("4");
		this.table1.Add (this.BN4);
		global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1 [this.BN4]));
		w10.TopAttach = ((uint)(1));
		w10.BottomAttach = ((uint)(2));
		w10.XOptions = ((global::Gtk.AttachOptions)(4));
		w10.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.BN5 = new global::Gtk.Button ();
		this.BN5.CanFocus = true;
		this.BN5.Name = "BN5";
		this.BN5.UseUnderline = true;
		this.BN5.Label = global::Mono.Unix.Catalog.GetString ("5");
		this.table1.Add (this.BN5);
		global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table1 [this.BN5]));
		w11.TopAttach = ((uint)(1));
		w11.BottomAttach = ((uint)(2));
		w11.LeftAttach = ((uint)(1));
		w11.RightAttach = ((uint)(2));
		w11.XOptions = ((global::Gtk.AttachOptions)(4));
		w11.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.BN6 = new global::Gtk.Button ();
		this.BN6.CanFocus = true;
		this.BN6.Name = "BN6";
		this.BN6.UseUnderline = true;
		this.BN6.Label = global::Mono.Unix.Catalog.GetString ("6");
		this.table1.Add (this.BN6);
		global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table1 [this.BN6]));
		w12.TopAttach = ((uint)(1));
		w12.BottomAttach = ((uint)(2));
		w12.LeftAttach = ((uint)(2));
		w12.RightAttach = ((uint)(3));
		w12.XOptions = ((global::Gtk.AttachOptions)(4));
		w12.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.BN7 = new global::Gtk.Button ();
		this.BN7.CanFocus = true;
		this.BN7.Name = "BN7";
		this.BN7.UseUnderline = true;
		this.BN7.Label = global::Mono.Unix.Catalog.GetString ("7");
		this.table1.Add (this.BN7);
		global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table1 [this.BN7]));
		w13.TopAttach = ((uint)(2));
		w13.BottomAttach = ((uint)(3));
		w13.XOptions = ((global::Gtk.AttachOptions)(4));
		w13.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.BN8 = new global::Gtk.Button ();
		this.BN8.CanFocus = true;
		this.BN8.Name = "BN8";
		this.BN8.UseUnderline = true;
		this.BN8.Label = global::Mono.Unix.Catalog.GetString ("8");
		this.table1.Add (this.BN8);
		global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table1 [this.BN8]));
		w14.TopAttach = ((uint)(2));
		w14.BottomAttach = ((uint)(3));
		w14.LeftAttach = ((uint)(1));
		w14.RightAttach = ((uint)(2));
		w14.XOptions = ((global::Gtk.AttachOptions)(4));
		w14.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.BN9 = new global::Gtk.Button ();
		this.BN9.CanFocus = true;
		this.BN9.Name = "BN9";
		this.BN9.UseUnderline = true;
		this.BN9.Label = global::Mono.Unix.Catalog.GetString ("9");
		this.table1.Add (this.BN9);
		global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table1 [this.BN9]));
		w15.TopAttach = ((uint)(2));
		w15.BottomAttach = ((uint)(3));
		w15.LeftAttach = ((uint)(2));
		w15.RightAttach = ((uint)(3));
		w15.XOptions = ((global::Gtk.AttachOptions)(4));
		w15.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.BPor = new global::Gtk.Button ();
		this.BPor.CanFocus = true;
		this.BPor.Name = "BPor";
		this.BPor.UseUnderline = true;
		this.BPor.Label = global::Mono.Unix.Catalog.GetString ("*");
		this.table1.Add (this.BPor);
		global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table1 [this.BPor]));
		w16.TopAttach = ((uint)(2));
		w16.BottomAttach = ((uint)(3));
		w16.LeftAttach = ((uint)(3));
		w16.RightAttach = ((uint)(4));
		w16.XOptions = ((global::Gtk.AttachOptions)(4));
		w16.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.BPunto = new global::Gtk.Button ();
		this.BPunto.CanFocus = true;
		this.BPunto.Name = "BPunto";
		this.BPunto.UseUnderline = true;
		this.BPunto.Label = global::Mono.Unix.Catalog.GetString (".");
		this.table1.Add (this.BPunto);
		global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table1 [this.BPunto]));
		w17.TopAttach = ((uint)(3));
		w17.BottomAttach = ((uint)(4));
		w17.LeftAttach = ((uint)(1));
		w17.RightAttach = ((uint)(2));
		w17.XOptions = ((global::Gtk.AttachOptions)(4));
		w17.YOptions = ((global::Gtk.AttachOptions)(4));
		this.vbox1.Add (this.table1);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.table1]));
		w18.Position = 1;
		w18.Expand = false;
		w18.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 160;
		this.DefaultHeight = 164;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.BPunto.Clicked += new global::System.EventHandler (this.OnBPuntoClicked);
		this.BPor.Clicked += new global::System.EventHandler (this.OnBPorClicked);
		this.BN9.Clicked += new global::System.EventHandler (this.OnBN9Clicked);
		this.BN8.Clicked += new global::System.EventHandler (this.OnBN8Clicked);
		this.BN7.Clicked += new global::System.EventHandler (this.OnBN7Clicked);
		this.BN6.Clicked += new global::System.EventHandler (this.OnBN6Clicked);
		this.BN5.Clicked += new global::System.EventHandler (this.OnBN5Clicked);
		this.BN4.Clicked += new global::System.EventHandler (this.OnBN4Clicked);
		this.BN3.Clicked += new global::System.EventHandler (this.OnBN3Clicked);
		this.BN2.Clicked += new global::System.EventHandler (this.OnBN2Clicked);
		this.BN1.Clicked += new global::System.EventHandler (this.OnBN1Clicked);
		this.BN.Clicked += new global::System.EventHandler (this.OnBNClicked);
		this.BMenos.Clicked += new global::System.EventHandler (this.OnBMenosClicked);
		this.BMas.Clicked += new global::System.EventHandler (this.OnBMasClicked);
		this.BIgual.Clicked += new global::System.EventHandler (this.OnBIgualClicked);
		this.BEntre.Clicked += new global::System.EventHandler (this.OnBEntreClicked);
	}
}
